POST http://localhost:5219/breakfasts
content-type: application/json

{
    "name": "Vegan Sunshine",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]  
}

###
GET http://localhost:5219/Breakfasts/970d1412-15aa-4f71-9279-e79ba9aa5197